spring:
  jpa:
    show-sql: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem://localhost/~/test;MODE=MYSQL;
      username: sa
      password:
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/TEST_DB
#      username: root
#      password: 1234
logging:
  level:
    org:
      hibernate:
        sql: info
        type.descriptor.sql.BasicBinder: trace
